### PR TITLE
fix(cms): fix optional tag/category for post

### LINKED ISSUE #80: No longer require tags/categories for post
Posts should not need a category/tag to be added before they can be published. This would be somewhat of a breaking change for people who rely on type definitions that are outdated then.

### PR DESCRIPTION
**Pull request by sidhuiwnl**
Fixes #80

Posts can now be created or updated without a category or tags.

image

## Summary by CodeRabbit

- New Features
  - Posts can be created and updated without adding tags; tags are now optional.
- Bug Fixes
  - Editing a post no longer clears or alters tags unless changed.
  - Tag selector handles empty or missing values more reliably, avoiding errors.
- Chores
  - Repository now ignores IDE settings (.idea).
  - Server-side tag validations added to ensure only valid workspace tags are accepted.

### CODE REVIEW

File: apps/cms/src/app/api/categories/[id]/route.ts [hunk 1]
```diff
@@ -50,5 +50,5 @@ export async function DELETE(
     },
   });
 
-  return NextResponse.json(deletedCategory.id, { status: 204 });
+  return NextResponse.json(deletedCategory.id, { status: 200 });
```
Comment (mezotv) [inline apps/cms/src/app/api/categories/[id]/route.ts]: Please keep this a 204
```suggestion
  return NextResponse.json(deletedCategory.id, { status: 204 });
```

File: apps/cms/src/app/api/posts/route.ts [hunk 2]
```diff
@@ -44,6 +44,8 @@ export async function POST(request: Request) {
 
   const values = postSchema.parse(await request.json());
 
+  console.log("for testing",values);
+
```
Comment (mezotv) [inline apps/cms/src/app/api/posts/route.ts]:
```suggestion
```

**Review by mezotv — CHANGES_REQUESTED** [review]
We actually decided that we will keep the category required and only make the tags optional, would you mind changing that in your PR too? Super sorry about not giving you a heads up I actually forgot someone was working on this.

Also left a few comments unrelated to the category ^^

File: packages/db/prisma/migrations/20250826194942_make_category_required/migration.sql [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+  Warnings:
+
+  - Made the column `categoryId` on table `post` required. This step will fail if there are existing NULL values in that column.
+
+*/
+-- DropForeignKey
+ALTER TABLE "post" DROP CONSTRAINT "post_categoryId_fkey";
+
+-- AlterTable
+ALTER TABLE "post" ALTER COLUMN "categoryId" SET NOT NULL;
```
[the remark this answers is not in the document]
Comment (taqh) [reply packages/db/prisma/migrations/20250826194942_make_category_required/migration.sql:11]: you yap too much

**Comment by sidhuiwnl** [comment]
sorry i didn't see the comment and reply to the changes.
